apiVersion: v1
kind: Namespace
metadata:
  name: static1
---
apiVersion: v1
kind: Namespace
metadata:
  name: static2
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/votre-repo/SunnyTech.git
    targetRevision: HEAD
    path: scenarios/01-basic-apps/static1
    plugin:
      env:
        - name: VAULT_ADDR
          value: http://vault.vault.svc:8200
        - name: ARGOCD_ENV_AVP_TYPE
          value: vault
        - name: ARGOCD_ENV_AVP_AUTH_TYPE
          value: k8s
        - name: ARGOCD_ENV_AVP_K8S_ROLE
          value: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: static1
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/votre-repo/SunnyTech.git
    targetRevision: HEAD
    path: scenarios/01-basic-apps/static2
    plugin:
      env:
        - name: VAULT_ADDR
          value: http://vault.vault.svc:8200
        - name: ARGOCD_ENV_AVP_TYPE
          value: vault
        - name: ARGOCD_ENV_AVP_AUTH_TYPE
          value: k8s
        - name: ARGOCD_ENV_AVP_K8S_ROLE
          value: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: static2
  syncPolicy:
    automated: {} 