apiVersion: v1
kind: Namespace
metadata:
  name: static1
---
apiVersion: v1
kind: Namespace
metadata:
  name: static2
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sribiere-wescale/lechatbotte.git
    targetRevision: HEAD
    path: scenarios/01-basic-apps/static1
  destination:
    server: https://kubernetes.default.svc
    namespace: static1
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sribiere-wescale/lechatbotte.git
    targetRevision: HEAD
    path: scenarios/01-basic-apps/static2
  destination:
    server: https://kubernetes.default.svc
    namespace: static2
  syncPolicy:
    automated: {} 