apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
        version: v1
    spec:
      serviceAccountName: vault-secret-manager
      initContainers:
      - name: vault-init
        image: alpine:latest
        command:
        - /bin/sh
        - -c
        - |
          # Installer les outils nécessaires
          apk add --no-cache curl jq kubectl
          
          # Récupérer les secrets depuis Vault
          echo "=== RÉCUPÉRATION DES SECRETS DEPUIS VAULT ==="
          
          # Récupérer le username
          USERNAME=$(curl -s -H "X-Vault-Token: dev-token-123" \
            http://vault.vault.svc.cluster.local:8200/v1/secret/data/test2/config | \
            jq -r '.data.data.username')
          
          # Récupérer le password
          PASSWORD=$(curl -s -H "X-Vault-Token: dev-token-123" \
            http://vault.vault.svc.cluster.local:8200/v1/secret/data/test2/config | \
            jq -r '.data.data.password')
          
          echo "Username récupéré depuis Vault: $USERNAME"
          echo "Password récupéré depuis Vault: $PASSWORD"
          echo "============================================="
          
          # Mettre à jour le secret Kubernetes existant
          kubectl patch secret example2 -n static2 --type='json' -p="[{\"op\": \"replace\", \"path\": \"/stringData/username\", \"value\": \"$USERNAME\"}, {\"op\": \"replace\", \"path\": \"/stringData/password\", \"value\": \"$PASSWORD\"}]"
          
          echo "Secret mis à jour avec succès dans Kubernetes"
        env:
        - name: VAULT_ADDR
          value: "http://vault.vault.svc.cluster.local:8200"
        - name: VAULT_TOKEN
          value: "dev-token-123"
      containers:
        - name: echo-server
          image: hashicorp/http-echo:alpine
          args:
          - "-text=App2 (Vault) - Username: $SECRET_USERNAME, Password: $SECRET_PASSWORD"
          ports:
            - name: http-port
              containerPort: 5678
          env:
          - name: SECRET_USERNAME
            valueFrom:
              secretKeyRef:
                name: example2
                key: username
          - name: SECRET_PASSWORD
            valueFrom:
              secretKeyRef:
                name: example2
                key: password
---
apiVersion: v1
kind: Service
metadata:
  name: echo-service
spec:
  selector:
    app: echo-server
  ports:
    - protocol: TCP
      port: 5678
      targetPort: 5678
  type: ClusterIP 