apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-secret-manager
  namespace: static2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-manager
  namespace: static2
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-secret-manager-binding
  namespace: static2
subjects:
- kind: ServiceAccount
  name: vault-secret-manager
  namespace: static2
roleRef:
  kind: Role
  name: secret-manager
  apiGroup: rbac.authorization.k8s.io 