apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  configManagementPlugins: |
    - name: argocd-vault-plugin
      init:
        command: [argocd-vault-plugin]
        args: ["init"]
      generate:
        command: [argocd-vault-plugin]
        args: ["generate"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server
  template:
    spec:
      initContainers:
      - name: install-argocd-vault-plugin
        image: curlimages/curl:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "=== Début de l'installation du plugin Vault ==="
          echo "Répertoire de travail: $(pwd)"
          echo "Contenu du répertoire /custom-tools:"
          ls -la /custom-tools || echo "Répertoire /custom-tools vide ou inexistant"
          
          echo "Test de connectivité réseau:"
          echo "Test DNS github.com:"
          nslookup github.com || echo "Échec de résolution DNS"
          echo "Test de connectivité HTTP:"
          curl -I https://google.com || echo "Échec de connectivité HTTP"
          
          echo "Tentative de téléchargement du plugin Vault:"
          curl -v -L -o /custom-tools/argocd-vault-plugin https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v1.18.1/argocd-vault-plugin_1.18.1_linux_amd64
          DOWNLOAD_EXIT_CODE=$?
          echo "Code de sortie du téléchargement: $DOWNLOAD_EXIT_CODE"
          
          echo "Vérification du fichier téléchargé:"
          ls -la /custom-tools/argocd-vault-plugin || echo "Fichier non trouvé"
          
          if [ -f /custom-tools/argocd-vault-plugin ]; then
            echo "Fichier trouvé, attribution des permissions:"
            chmod +x /custom-tools/argocd-vault-plugin
            echo "Permissions appliquées:"
            ls -la /custom-tools/argocd-vault-plugin
          else
            echo "ERREUR: Le fichier n'a pas été téléchargé"
            exit 1
          fi
          
          echo "=== Fin de l'installation du plugin Vault ==="
        volumeMounts:
        - name: custom-tools
          mountPath: /custom-tools
      containers:
      - name: repo-server
        env:
        - name: VAULT_ADDR
          value: "http://vault.vault.svc.cluster.local:8200"
        - name: VAULT_TOKEN
          value: "dev-token-123"
        volumeMounts:
        - name: custom-tools
          mountPath: /usr/local/bin/argocd-vault-plugin
          subPath: argocd-vault-plugin
      volumes:
      - name: custom-tools
        emptyDir: {} 