apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/name: vault
  name: vault-server-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: vault
  namespace: vault-auth-delegator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault
  namespace: vault-auth-delegator
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: vault-auth-delegator
  annotations:
    kubernetes.io/service-account.name: vault
type: kubernetes.io/service-account-token 